### PR TITLE
Add patch to extend AntennaRange ranges.

### PR DESCRIPTION
**Pull request by Kerbas-ad-astra**
Since the system is 10x bigger, the antenna ranges have to get 10x boosts.

### CODE REVIEW

**Comment by Kerbas-ad-astra** [comment]
Is this of interest to you?

**Comment by NathanKell** [comment]
Ah! Sorry! This was during my lack-of-net-access period, and I totally missed it.

**Comment by NathanKell** [comment]
Uh FINAL is a really bad idea for this IMO, that means that nothing else will be able to modify the ranges. Do you mean something like AFTER[AntennaRange] ?

**Comment by Kerbas-ad-astra** [comment]
I did have that at one of the "intermediate" commits, and it should work for most cases, since AR patches are usually added during the "Legacy" block or "FOR[AntennaRange]", but there's the possibility that it might miss AR patches that are added AFTER[some mod that comes after AR in the alphabet, which is most of them] -- I can't imagine why anyone would apply their AR patches then, but that doesn't mean it won't happen.  Since it's multiplying ranges rather than replacing them, I don't think it's a huge deal, but I'm alright with putting it back to after AR if you're concerned.

**Comment by NathanKell** [comment]
Hmm. I guess the danger is having a specific patch that does something finer-grained than multiplying by 10, that this then overrides. But if you don't think that's likely, that's fine as is.

**Comment by Kerbas-ad-astra** [comment]
I wouldn't say "overrides" as much as "amplifies" (or possibly is overwritten by).

That being said, it probably is better practice to leave FINAL for stuff that has more need than us of coming last, so I've put it back to AFTER[AntennaRange].  There's few enough antennas in the world that they'll probably all get patched at the right time. :)

**Comment by NathanKell** [comment]
Sounds good, in it goes! :)

**Pull request merged**
