### PR TITLE
RSS Kopernicus updates

### PR DESCRIPTION
**Pull request by PhineasFreak**
**Change Log:**

* Update all body configs to be compatible with the latest Kopernicus changes. The **displayName** field now holds the visible name of the body.
* Use a new noiseType for Deimos and Callisto, since the "Perlin" one caused major problems. **This is not my work! Give full credit to @Sigma88 and @Galileo88 for figuring out the actual cause of the problem and the necessary fixes for it.**
* Formatting updates (newlines, space to tab, trailing spaces)

[**Alternate diff ignoring whitespace changes**](https://github.com/KSP-RO/RealSolarSystem/pull/108/files?w=1) **(use this for the correct git diff)**

### CODE REVIEW

**Comment by Sigma88** [comment]
this might not be required following the release of Kopernicus 1.3.0-2

**Comment by NathanKell** [comment]
Per https://github.com/Kopernicus/Kopernicus/issues/177 I'd really prefer if we still kept renaming Earth, although explicitly stating displayname doesn't hurt. Are the noise changes back-portable to 1.2.2? If so I'd like to release an updated RSS for 1.2.2 as well one for 1.3. It's great y'all figured out how to fix the Martian moons!

**Comment by Sigma88** [comment]
@NathanKell kopernicus 1.3.0-2 just added checks to make sure old noise syntax can be fed to KSP 1.3.0 without explicitly changing the cfg


which means there is no need to change the noise anymore

**Comment by PhineasFreak** [comment]
@Sigma88 i tested the original (KSP 1.2.2) configs and they still had the same issue (Callisto covering the entire universe). I was happy to see a new version but unfortunately it did not help.

@NathanKell per the Kopernicus documentation we can still define the **cbNameLater = Earth** field. In fact, i forgot to port it over.

**Comment by NathanKell** [comment]
Ah, so I'm a bit confused now. Are any of the PQS changes 1.2-relevant? Or was the fix to the terrain only a fix to a 1.3 problem?

**Comment by PhineasFreak** [comment]
@NathanKell the PQS fixes are for KSP 1.3. The existing Kopernicus configs work perfectly for KSP 1.2.

**Edit:** i am not sure though how is the best way to handle this. The new configs are not backwards compatible (meaning that you cannot drop them in the place of the previous KSP 1.2 ones) but they should not have any adverse effects on the save files. In fact, i did some testing with an even older (KSP 1.1.3) save and it loaded just fine.

**Comment by NathanKell** [comment]
Cool!

**Comment by Sigma88** [comment]
@stolld it looks like your changes were not enough to get rid of the RSS issues on 1.3

[output_log.txt](https://github.com/KSP-RO/RealSolarSystem/files/1039740/output_log.txt)

**Comment by StollD** [comment]
I already said it multiple times: 1.3 updated the library that is used by the PQS mods to generate the terrain. If this library is now working differently, the only way to change it would be to rewrite the PQSMod using the old library and to load it with ModLoader

**Comment by PhineasFreak** [comment]
@StollD so all these changes are pretty much required by Kopernicus 1.3.0, right? Just to be 100% sure.

**Comment by Sigma88** [comment]
@StollD ah nevermind then, I thought it was something like the clamp on octaves
I'll close the issue on kopernicus then :)

**Comment by StollD** [comment]
@PhineasFreak You can keep useTheInName, in Kopernicus 1.3.0-x it just sets displayName to "The" + bodyName.

Also, if the bodyName equals the displayName, you dont need to specify displayName, it gets set automatically

**Comment by PhineasFreak** [comment]
@StollD well, consider it as a "consistency" thing. I like to have explicit declarations for most things. :wink:

**Review by CoderChang65535 — APPROVED** [review]

**Pull request merged**
