### PR TITLE
Update RSS_TerrainDetailPresets.cfg

### PR DESCRIPTION
**Pull request by vader111**
Update RSS_TerrainDetailPresets.cfg to add missing entries.

### CODE REVIEW

**Comment by siimav** [comment]
Any explanation on what these entries do or what they're supposed to change?

**Comment by vader111** [comment]
adds the missing terrain details

**Comment by vader111** [comment]
the game bitches at me for the missing presets

**Comment by siimav** [comment]
As far as I can tell, this PR will add the following options to Terrain detail slider:
* RSS Low Res
* RSS default res
* (Another) RSS default res
All the stock options are still there but the RSS High Res doesn't show up.

**Comment by vader111** [comment]
> 
> 
> As far as I can tell, this PR will add the following options to Terrain detail slider:
> 
>     * RSS Low Res
> 
>     * RSS default res
> 
>     * (Another) RSS default res
>       All the stock options are still there but the RSS High Res doesn't show up.

yeah let me fix that

**Pull request closed without merging**
