### PR TITLE
updated height of FR - Kourou because of terrain clipping

### PR DESCRIPTION
**Pull request by rsparkyc**

### CODE REVIEW

**Comment by rsparkyc** [comment]
Meant to do this to the main RSS

**Comment by rsparkyc** [comment]
Actually maybe this is the right fork to use?

**Comment by jbengtson** [comment]
Are you using High Terrain Detail in KSP settings?  I have seen zero issues with Kourou.  Can you describe exactly what is happening?

**Comment by rsparkyc** [comment]
Ahh, I was only on the default setting.  That seemed to fix it!

**Pull request closed without merging**
