### PR TITLE
RSS asteroids

### PR DESCRIPTION
**Pull request by PhineasFreak**
- Fix Near Earth Object (NEO) spawning (before it would be in a very low orbit around the Sun).
- Add an asteroid belt (between Mars and Jupiter).

### CODE REVIEW

**Comment by stratochief66** [comment]
Nice!

Any chance you could post a few pics?
Did you do this with RSS in 1.1, or 1.1.1?

**Comment by PhineasFreak** [comment]
@stratochief66 this was with KSP 1.1 (have not updated yet to 1.1.1 since that broke Kopernicus). I forgot to post the screenshots, i will get them in a couple of hours!

Edit: i have a ~~slightly older screenshot~~ (before implementing the LAN parameter).

**Comment by PhineasFreak** [comment]
And a newer ~~screenshot~~.

Note the high inclination of some of the real asteroids (2 Pallas is located at the top - above the Earth - and Chariklo is located at the right - visually intersecting the orbit of Jupiter).

**Comment by KillAshley** [comment]
very nice dude. tested in latest Kopernicus 1.0.3 for 1.1.2 and works beautifully. Nice work!

**Comment by NathanKell** [comment]
This is awesome! Thanks so much! :)

**Pull request merged**
