### PR TITLE
[Maintenance] KSP 1.6 branch updates

### PR DESCRIPTION
**Pull request by PhineasFreak**
**Change Log:**

* Set the CommNet ground station parameters to the appropriate values for RSS (covers some of the requirements of PR https://github.com/KSP-RO/RealSolarSystem/pull/151).
* Add an installation checker (checks the GameData directory for the existence of the "RSS-Textures" folder, if it is missing then it will warn the user).
* Fix the broken hyperlink of the Version Checker KSP forums page.
* Update the version checker for KSP 1.6.
* Remove the obsolete x64 check method from the version checker.
* Simplify the operation of the watchdog routine (will now only operate in the Space Center and Flight scenes by default). Courtesy of @siimav.
* Add some white space for better readability.

**Notes:**

* The CommNet range and occlusion settings require a KSP restart before they are applied in-game.

### CODE REVIEW

**Comment by siimav** [comment]
Tested under KSP 1.6.1 and everything appears to be working as intended

**Comment by siimav** [comment]
Couple of more ideas for improving the code:
* Instead of doing the LoadScene checks in RSSWatchDog, only make it start up in flight and KSC scenes
* In RSSCommNetSettings destroy the object after it has done it's thing
* Remove the CompatibilityChecker altogether?

**Comment by PhineasFreak** [comment]
I cannot really comment on the first two as, to be honest, i have no idea what they mean. For the CC, i did try to do a small "poll" about it in the KSP-RO Discord but nobody responded and got buried very quickly. I did consider removing it as there were no code-breaking changes in the last few KSP versions (and Kopernicus does a much better job locking RSS compatibility than us).

**Comment by PhineasFreak** [comment]
@siimav I believe i have tackled most of the outstanding issues that you pointed out.

Some things that would like to have feedback upon:

* Should the CommNet routine only execute once? Currently it updates the parameters every time the Space Center scene is loaded but i do not think that this is a sensible choice.
* Should the version check feature be removed?
* The assembly version is currently marked as 0.15.0. The last few RSS releases used the KSP version to ease compatibility identification (0.13.0 for KSP 1.3.1, 0.14.0 for KSP 1.4.5). Should we skip the 0.15.0 version and update it to 0.16.0?

**Comment by siimav** [comment]
Thanks, these latest changes look good.

* The only issue I see with the CommNet routine is that if the user wants to set the range modifiers to something other than 1 then these will get reset as soon as the space center scene is visited again. But values other than 1 do not work properly so that's probably something that shouldn't be changed at all? It's possible that it could be implemented with ```GameEvents.OnGameSettingsApplied``` events but that would just be a lot more complicated than it's worth. 
* You probably know that I would support removing that version check code. I don't really see it doing anything useful because the RSS textures would still load up on incompatible versions. And it would be a bit confusing to the user because he will get a partially working install as some of the functionality that's implemented in code would just silently not work. Maybe some other modder would have valid arguments on why keeping it inside the code would be good. I just can't currently find any.
* Your version number proposal makes sense. I don't see any issues with skipping a minor version and updating directly to 0.6.

**Comment by MikeOnTea** [comment]
I'd also lean towards removal of the checker, as i can remember the dialog being a bit annoying to myself in the early 1.3 days even though the mod worked fine.

**Comment by PhineasFreak** [comment]
@siimav I have tagged the CommNet fixer to patch the parameters only the first time the SpaceCenter scene is loaded. At least this will give the user the ability to change them any time afterwards, although it will not persist between KSP sessions.

**[It occurred to me that RP-1 has a much better way of handling these parameters ](https://github.com/KSP-RO/RP-0/blob/master/GameData/RP-0/GameParameters.cfg)** (it even includes the above CommNet presets). Looks simple enough to be adapted as part of RSS but i am not sure about possible conflicts upon save game load. It also does not allow any in-game changes by the user to persist between sessions so back to square one.

**Comment by siimav** [comment]
I vaguely remember that settings some of the parameters through the RP-1 GameParameters.cfg does not work. I think it only works for settings implemented the *classic* way but the CommNet settings are done with the GameParameters.CustomParameterNode.
It's probably also possible to store some boolean flag inside the RSSCommNetSettings which gets set to true on starting a new career and then afterwards using it to check whether overriding the custom settings should be done.

**Comment by PhineasFreak** [comment]
The flag sounds like a good way to implement that (IIRC TACLS also does something similar). We could even use it as a toggleable option under the "REALSOLARSYSTEM" node. That way we can always override the settings (since values other than "1.0" for the ranges will be invalid) for "standard" RSS but the users/modders (like SSRSS) will have the ability to patch that toggle via MM.

**Edit:** Yep, it is a much better system overall! I moved all three parameters inside the global RSS configuration file. That way both RSS and any other interested party can freely set their own CommNet parameters without conflicts.

**Pull request merged**
