### PR TITLE
Add Kopernicus Expansion Bootprint Support

### PR DESCRIPTION
**Pull request by Its-Just-Luci**
Adds Kopernicus Expansion Bootprint Support by adding the line:

allowFootprints = true

to the PQS section

### CODE REVIEW

**Comment by siimav** [comment]
What the hell is going on in that commit?

**Comment by vader111** [comment]
Just make a MM patch

**Comment by Its-Just-Luci** [comment]
> What the hell is going on in that commit?

I just added 1 line to all non-atmospheric bodies in the solar system

**Comment by siimav** [comment]
Adding *just 1 line* to every RSS body shouldn't equate to 100 files changed and 9,449 lines added.

**Comment by vader111** [comment]
@Its-Just-Luci Well this PR requires another mod that isn't included with RSS so a MM patch would be the better way of adding this function.

**Comment by siimav** [comment]
Would you mind using a branch instead of continuously updating this PR?

**Comment by siimav** [comment]
Closing this PR since it no longer has absolutely anything to do with the original goal.
PS: learn to use branches

**Pull request closed without merging**
