### PR TITLE
Adding ribbons for new bodies (Ceres, Vesta, moons of Uranus).

### PR DESCRIPTION
**Pull request by Kerbas-ad-astra**

### CODE REVIEW

**Comment by ec429** [comment]
Uh, most of those Uranian moon ribbons are blank white.  Missing layer somewhere?

**Comment by Kerbas-ad-astra** [comment]
Seems I goofed the layers a little...thanks for the heads-up.

**Comment by Kerbas-ad-astra** [comment]
By the way, many thanks for your ribbonator!  I made a modified version to iterate through all of the body/atmosphere combinations to generate these ribbons (no way was I going to make them all by hand).

**Comment by ec429** [comment]
Thank *you* for putting them in the game!  Now if only there were a "FF for probes"...

**Comment by PhineasFreak** [comment]
So, is everything OK for a merge?

**Comment by ec429** [comment]
I think so, yes.  (I apparently don't have +w bits on RSS, or I'd do it.)

**Comment by Kerbas-ad-astra** [comment]
All good.

**Comment by ec429** [comment]
@Kerbas-ad-astra btw, would you consider posting your new ribbon backgrounds for these bodies as a ribbonator PR?  (I don't know whether they're divisible by three, but the layout will probably need a redesign anyway...)

**Pull request merged**
