### PR TITLE
Update CustomAsteroids.cfg

### PR DESCRIPTION
**Pull request by miki-g**
fix kerbin => earth
move trojans and greeks to correct orbit phase

### CODE REVIEW

**Comment by PhineasFreak** [comment]
I had to make a minor addition to the config in order for CustomAsteroids not to throw a NullRef by adding:

```
!INTERCEPT,*{}
```

to the RSS patch (removes a reference to the body Kerbin). But then KSP hangs upon loading a save file and the log is spammed by the asteroid generator spawner:

```
[LOG 23:19:13.199] [CustomAsteroids]: Asteroid driver started.
[LOG 23:19:13.200] [FixedRateSpawner]: asteroid discovered at UT 1459.0237580146
[LOG 23:19:13.202] [CustomAsteroids]: drawing orbit from MainBeltZoneI
[LOG 23:19:13.203] [CustomAsteroids]: new orbit at 329592831649.303 m, e = 0.0996832860357732, i = 19.8532643792087, aPe = 203.678695678711, lAn = 3.31, mEp = 4.74380575913214 at epoch 0
[LOG 23:19:13.206] [FixedRateSpawner]: New object found: Zone I Main Belt Ast. HFV-264 in asteroid set MainBeltZoneI.
[LOG 23:19:13.209] [FixedRateSpawner]: asteroid discovered at UT 10879.2163028208
[LOG 23:19:13.209] [CustomAsteroids]: drawing orbit from JupiterGreeks
[LOG 23:19:13.210] [CustomAsteroids]: new orbit at 778189318889.362 m, e = 0.0790464849173082, i = 22.5421639946158, aPe = 299.896545410156, lAn = 3.26, mEp = -4.51350203811674 at epoch 0
[LOG 23:19:13.211] [FixedRateSpawner]: New object found: Trojan Ast. Leading DIT-254 in asteroid set JupiterGreeks.
[LOG 23:19:13.212] [FixedRateSpawner]: asteroid discovered at UT 51219.4349031907
[LOG 23:19:13.212] [CustomAsteroids]: drawing orbit from JupiterTrojans
[LOG 23:19:13.213] [CustomAsteroids]: new orbit at 778189318889.362 m, e = 0.080953473040286, i = 23.3708238135863, aPe = 28.1453857421875, lAn = 3.26, mEp = -1.82312031582732 at epoch 0
[LOG 23:19:13.214] [FixedRateSpawner]: New object found: Trojan Ast. Trailing KUA-465 in asteroid set JupiterTrojans.
[LOG 23:19:13.215] [FixedRateSpawner]: asteroid discovered at UT 52508.9829222471
[LOG 23:19:13.215] [CustomAsteroids]: drawing orbit from Plutinos
[LOG 23:19:13.216] [CustomAsteroids]: new orbit at 5893330340929.55 m, e = 0.201417967677116, i = 19.5132324246288, aPe = 184.494537353516, lAn = 44.4355583190918, mEp = 2.42201158705645 at epoch 0
```

Some thousands of these...

**Comment by raidernick** [comment]
@PhineasFreak so what's up with this is it good to merge for the next release?

**Comment by Kerbas-ad-astra** [comment]
This appears to be redundant with #128.

**Comment by miki-g** [comment]
we dont need this bugfix after complex update #128 ( maybe :D )

**Pull request closed without merging**
