### PR TITLE
Mars mk1

### PR DESCRIPTION
**Pull request by stratochief66**
Added a functional Mars. The ground and atmosphere could likely still
use some tweaking. The pressure and temperature curves have been
converted and included.

### CODE REVIEW

**Comment by NathanKell** [comment]
You're, uh, assigning a vertex color map twice.

**Comment by stratochief66** [comment]
I see VertexColorMap, VertexColorMapBlend, and VertexColorSolid. Which should be removed?

**Comment by NathanKell** [comment]
VertexColorMap. Why were you adding it in the first place, actually? RSS exclusively uses VertexColorMapBlend, except in cases where the blend value is 1.0 (which means they are equivalent). If the body already has VertexColorMap, though, it needs to get removed, but I don't think Duna does.

**Comment by stratochief66** [comment]
How might I see what parameters the pre-existing planets/templates had?

**Comment by stratochief66** [comment]
Is there a place I can look up (ie documentation) on what each of the PQS actually does, or a way to change their values in game?

**Comment by NathanKell** [comment]
https://www.dropbox.com/s/x95wxmnbd7metxs/Components.zip?dl=0
Note that names aren't given, alas, but types and values are, and usually there's only one instance of each PQSMod.

**Comment by stratochief66** [comment]
Thanks! Reviewing those, as it is pretty handy to know what a template contains.

Also pasting this as a potentially useful reference:
http://kerbal-tutti.blogspot.ca/2015/03/how-to-make-planets-with-kopernicustech.html

**Comment by NathanKell** [comment]
Regarding seeing what they do: Uh, not really other than digging into KSP. Well, you could install Kittopia on KSP 0.90 and use the interactive editor to play around with adding and changing PQSMods. That could work.
Oh, and https://github.com/NathanKell/RealSolarSystem/wiki/PQSMods-supported-in-the-cfg

**Comment by NathanKell** [comment]
Yeah, any references for Kopernicus would work too. They have subtly different names for things than RSS did (apart from stripping PQSMod_ from mod names)

**Comment by NathanKell** [comment]
Uh, that tutorial is...problematic.

**Comment by stratochief66** [comment]
True, but it did have some comments explaining some of the values. Any idea what PQSLandControl does? Why do we always disable it?

**Pull request closed without merging**
