### PR TITLE
Update LaunchSites.cfg

### PR DESCRIPTION
**Pull request by miki-g**
pull base from underground ... again :)

### CODE REVIEW

**Comment by NathanKell** [comment]
I'm confused. What level of terrain detail are you using? Also, which texture pack? Because the Cape is one of the few sites, as far as I know, that is _not_ broken...

**Comment by miki-g** [comment]
ok, i try some settings changes in details and send report to you
maybe low details make this issue

**Comment by miki-g** [comment]
i use before this problem low terain details because
terrain details is not my priority when playng kerbal ;)
... thats all
(texture relsolution is irelevant in this problem)

**Comment by miki-g** [comment]
in rss,

i have added airports
Mbandaka ~2km from equator (equator closest airport in the world)
Entebe ~3km (Lake Victoria, Uganda)
Macapa ~5km (Brasil, amazon delta)
Sao Tome ~42km (equatorial island near africa)
Singapore ~150km

and some fiction :D

south pole,
Isla Isabela (equatorial island in pacific, ~740km from ecuador)
and ... mount everest ... ?
(add fiction bases? or not? only real airports)

before updating launchsites.cfg - one question (:
you prefer real coordinates and altitude of existing airports?
or match altitude and also sometime small adjust coordinates to pass with
heightmap in rss?

because real map and rss heightmap is diferent, many inaccuracies :\

(for example, mount everest have in rss over 16km, and coordinates dont
match)

btw. in future, is planned update accuracy (and maybe resolution) of
heightmaps?

**Pull request closed without merging**
