### PR TITLE
Update Earth.cfg

### PR DESCRIPTION
**Pull request by miki-g**
pull base from underground ... again :)

### CODE REVIEW

**Comment by stratochief66** [comment]
Main Menu -> Settings -> Graphics -> Terrain Detail to High should place KSC perfectly at ground level for you, unless there may be a difference between the different planet texture qualities ( @NathanKell )

I tested your KSC settings myself, and it caused the site to float above the ground for me (medium RSS textures, Terrain Detail = High).

That said, @NathanKell might there be a way for RSS to either:
1. Store these values and apply them differently depending on the Terrain Detail settings?
or
2. Change the terrain detail setting when RSS is loaded? 

Is there a good reason that in RSS terrain detail -shouldn't- always just be at High?

**Comment by NathanKell** [comment]
For 1, someone would need to rewrite PQSCity to be able to do that I think. For 2, hmm. I guess it might make older computers choke?

**Comment by stratochief66** [comment]
How potato would your computer have to be to suffer an issue? Would that be a CPU bound or GPU bound problem. One time cost, or continual cost? I'm trying to learn all the things :P

**Comment by NathanKell** [comment]
CPU cost since the quads are created and transformed on the CPU. Slight GPU cost because it's more stuff to render. If you want an example, compare FPS on Earth's surface vs the Moon's: Earth has a whole second PQS, doubling the visible quads. That's called ( oh hi @jbengtson ) ocean lag.

**Comment by miki-g** [comment]
pfff, no way to delete my own pull requests on github? :\

**Comment by NathanKell** [comment]
You can close it, that's effectively deleting it while still preserving the conversation. :)

BTW please don't get discouraged! We love it that you're helping out! It's just this site is fixable by means of running the recommended detail level (and yes, strato's right I need to look into flexibility there)

**Comment by miki-g** [comment]
i use before this problem low terain details because
terrain details is not my priority when playng kerbal ;)
... thats all
(texture relsolution is irelevant in this problem)

**Pull request closed without merging**
