### PR TITLE
Add recovery zones for NIMBY

### PR DESCRIPTION
**Pull request by Kerbas-ad-astra**
There's a mod called NIMBY (Not In My BackYard) that prevents vessel recovery unless you're within a recovery zone (defined by a config file, similar to launch sites or ground stations) or within range of a recovery vehicle (a vehicle with a science lab, an antenna, and an engineer on board).  This file defines recovery zones at each RSS launch site and ground station.

I had initially picked 500 km as the recovery range, based on the landing sites of the Mercury-Redstone missions (upper figure), but increasing the range to 1000 km results in nice contiguous recovery zones (lower figure):

launchsites_and_groundstations

launchsites_and_groundstations_1000

### CODE REVIEW

**Comment by PhineasFreak** [comment]
I do not think that it is possible to patch the NIMBY beacon locations anymore via MM. From the magico13 Modlets KSP 1.4.1 release notes:

> Mostly just a recompile and version bump. NIMBY moved the Beacons.cfg file into PluginData.

And i took a quick look at the source code to verify:

https://github.com/magico13/Modlets/blob/master/NotInMyBackYard/NotInMyBackYard.cs#L20

So it seems that the RSS patch will never be able to apply the custom beacons. Theoretically we could supply this patch as an "Extra" so that:

* A user can manually add/overwrite the existing NIMBY beacons.
* CKAN can use it as an optional recommended mod (like the DistantObjectEnhancement RSS config).

As a sidenote: **what the hell is going on with all these mod config files getting locked behind the PluginData wall?** I do realize that they are forcing MM cache reloads but with these specific files should only happen once (upon mod installation).

**Comment by Kerbas-ad-astra** [comment]
linuxgurugamer has adopted magico13's modlets, and has accepted (and incorporated into a release, for KSP 1.4.x to 1.6.x) my PR that changes the loading to a config file like KSCSwitcher: https://github.com/linuxgurugamer/Magico13_Modlets/pull/1

**Comment by PhineasFreak** [comment]
Oh, OK then, i will get the newer release, test it and report back.

**Comment by PhineasFreak** [comment]
I tried most major launch sites and some auxiliary ones. Everything checks out fine, although i am not sure if tracking stations could be considered recovery zones.

Also, thank you for bringing that mod into my attention (and adding one more restriction into my career mode games)!  :yum:

**Comment by Kerbas-ad-astra** [comment]
Tracking stations themselves probably don't have recovery crews, but I figure they're decent enough proxies for the kind of infrastructure required for spacecraft recovery, and I wanted to give the player just a little more target surface area.

**Pull request merged**
