### PR TITLE
new launch sites

### PR DESCRIPTION
**Pull request by miki-g**
real airports near equator,

and some fiction (South Pole, Isla Isabela, and (: lol sorry :) Mount Everest)

### CODE REVIEW

**Comment by stratochief66** [comment]
IIRC, the Launch Site list in RSS only includes sites that have produced
launches achieving orbit. @NathanKell?

That said, I don't think a list of launch sites for enjoyable airplane
flying is a bad idea at all. @NathanKell, is there a way M could distribute
these locations outside of modifying the RSS LaunchSites.cfg file that
would be compatible with RSS/KSCSwitcher?

**Comment by miki-g** [comment]
i pull this because people [want this](http://forum.kerbalspaceprogram.com/index.php?/topic/50471-105-real-solar-system-v1062-mar-15/&do=findComment&comment=2473946)

**Comment by raidernick** [comment]
@stratochief66 I don't have a problem if they "unofficially" distribute them on the forum, but allowing distribution on git or as an alternate file in the git is beyond unfair considering how I was shot down about adding white sands, which has immense historical significance to spaceflight but "can't" be added because of that orbit technicality. I feel that this is much more important than adding airports and if a change is ever considered in the future regarding this, white sands should be at the top of the list for anything new added.

**Comment by NathanKell** [comment]
Apologies, been busy on 1.1. Raidernick is right: I'm very happy to have people offer additional sites as a download themselves, but I would like to keep RSS itself to only having sites that have successfully orbited things.

**Comment by stratochief66** [comment]
@raidernick please take the time to read my comment before responding with such vitriol.

The RO doesn't control 'Github', and I made no suggestion that @miki-g add his sites to RSS. He can distribute whatever he likes through Github, or the forum, or any other website he chooses.

I was asking if there was a technical way his independently distributed sites could be compatible with KSCSwitcher.

Edit:
@NathanKell STS-3 (an orbital Shuttle mission) landed at Whitesands, isn't that enough to qualify it? :P
https://en.wikipedia.org/wiki/White_Sands_Space_Harbor

**Pull request closed without merging**
