### PR TITLE
Prevent missing tiles on suborbital flights

### PR DESCRIPTION
**Pull request by siimav**
Detect suborbital flights and force procedural quads to be recalculated. It does freeze the game for a fraction of a second while this is being done. So It's not really a perfect fix but based on my own testing and some feedback from others, it appears to be preventing any missing tiles.

### CODE REVIEW

**Review by PhineasFreak — COMMENTED** [review]
Hopefully i will be able to do a recompile for KSP 1.6.1 and test this by the end of the week.

**Comment by PhineasFreak** [comment]
Apparently it took me more than 1 week to actually test this...and i am sorry. On the bright side i can confirm that it fixes the missing PQS tiles (did various tests with high speed/high warp reentries)! Kudos to @siimav for implementing this fix, you are awesome!

Now, to decide whether i should break this PR by trying to merge the rest of the KSP 1.6 codebase changes...

**Comment by siimav** [comment]
If you have issues with getting this merged, then I could force-push an updated commit after you merge the other PR.

**Comment by PhineasFreak** [comment]
On a semi-related note, does any other planet mod experience that? Should this fix be part of Kopernicus in the near (or far) future?

**Comment by siimav** [comment]
I guess this issue could also happen on other planets although it's kinda hard to create suborbital flights on somewhere other than Earth. Testing it would probably require some sounding rocket launches on Mars. :)
I'm not so sure about getting this workaround integrated into Kopernicus. As far as I have heard, it appears to only happen in RSS. I'm not 100% sure though as I haven't played with other rescaled planetary packs.

**Comment by PhineasFreak** [comment]
**[Found one instance of that in stock KSP](https://www.reddit.com/r/KerbalSpaceProgram/comments/aq7inh/glidy_boi)** so it looks like that it can happen even without RSS.

**Pull request merged**
