### PR TITLE
[Bugfix] Ceres - Vesta - Uranian moons normal maps

### PR DESCRIPTION
**Pull request by PhineasFreak**
**Change Log:**

* Update the Kopernicus configs for compatibility with the new textures (https://github.com/KSP-RO/RSS-Textures/pull/19).

### CODE REVIEW

**Comment by raidernick** [comment]
@PhineasFreak I finally had time to test your fixes. The shading/lighting problem seems to be fixed but the ground is totally FUBAR now. When you are close enough to the ground to cause the game to transition from the far lod to the near lod(or w/e ksp calls it) for the ground, all the bodies you changed have these massive floating polygons coming out of the surfaces.

https://i.imgur.com/2Ux332b.png

**Comment by Kerbas-ad-astra** [comment]
Which body is that and how did you get there?  I tried them all (on KSP 1.3.1) just now and didn't have any issues, except for once where I 'warped' to Miranda at the minimum safe SMA and went 'poof' (later warps to Miranda were successful).

**Comment by raidernick** [comment]
it was ceres and i flew there. It also happened when i teleported to vesta though.
It only happens at the horizon, once i get close to the polygons they vanish. They also vanish if you are further from the surface to where it isn't rendered anymore.

**Comment by PhineasFreak** [comment]
These are the "floating tiles", an elusive bug that affects modded KSP bodies. It does not happen for everyone and when you try to debug it you end up with nothing.

The latest but report for that: https://github.com/KSP-RO/RealSolarSystem/issues/137 (the screenshot unfortunately is not clear enough though).

**Edit:** for comparison, here are two Ceres screenshots, one in low orbit and one on the surface:

* **Ceres Low Orbit (~42.5 km)**
* **Ceres Surface**

Also, normal maps do not affect the PQS appearance, only the ScaledSpace one. You could safely remove the normal maps and it would not make any difference. Only the height maps (and/or the various PQS mods) have the ability to do so.

**Edit:** removed sample screenshots.

**Comment by Kerbas-ad-astra** [comment]
Yeah, the last time I encountered that issue was when I was tinkering with Earth's PQS configs for KSP 1.4, but even then it was just during one run.  I've tried these new textures in both 1.3.1 and 1.4.2, warping to high orbit and then descending into range to get the actual terrain, and I've not had any trouble.

**Comment by raidernick** [comment]
@PhineasFreak if that's the case then, these prs are good to merge and we can get new releases out?

**Comment by EstrelaGaliza** [comment]
''The latest but report for that: #137 (the screenshot unfortunately is not clear enough though).''

I took better pictures. It happens to me every single launch if I reentry from suborbital flight (poligons dissapear at 140km) close to Cape or Baikonur (I suppose it affects any launch site)

image
image

Sometimes im able to find the missing terrain tiles 400 km west from KSC.

**Pull request merged**
